version: "3"

services:
  mysql:
    image: mysql:8.4.2
    container_name: expense-tracker
    environment:
      MYSQL_ROOT_PASSWORD: expense-tracker
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql